/*
 * Vidyarthi.ai course catalogue — v2 data model
 *
 * IMPORTANT:
 * - Keep this file UI-agnostic. The existing V7.1 cards can continue to use
 *   the legacy fields below while newer features use the richer fields.
 * - Do not publish a course unless status === "published" and the provider URL
 *   has been checked by a human.
 * - affiliateUrl is optional and must only be used where a commercial
 *   relationship exists and the listing is disclosed.
 */
window.VIDYARTHI_COURSES = [
  /* ---------------- Existing catalogue entries ---------------- */
  {
    id: "ai-free-01",
    title: "AI for Everyone",
    title_i18n: { en: "AI for Everyone", hi: "सभी के लिए AI", bn: "সবার জন্য AI" },
    provider: "Vidyarthi.ai",
    providerUrl: "",
    affiliateUrl: "",
    category: "ai",
    language: ["English", "Hindi"],
    level: "Beginner",
    price: 0,
    priceLabel: "free",
    type: "free",
    delivery: "internal",
    mode: "self-paced",
    duration: "Self-paced",
    durationHours: null,
    certificate: false,
    noCodingNeeded: true,
    aiForNonTech: true,
    careerOutcome: "Build basic AI literacy and understand where AI can help in study and work.",
    lastVerified: "2026-09-21",
    status: "draft",
    sourceType: "vidyarthi_original",
    rating: "4.8",
    students: "Free",
    featured: true,
    image: "https://images.pexels.com/photos/5940833/pexels-photo-5940833.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "A friendly starting point for understanding artificial intelligence without a technical background.",
    description_i18n: {
      en: "A friendly starting point for understanding artificial intelligence without a technical background.",
      hi: "बिना तकनीकी पृष्ठभूमि के AI को समझने की आसान शुरुआत।",
      bn: "প্রযুক্তিগত পটভূমি ছাড়াই AI বোঝার সহজ শুরু।"
    },
    url: "#"
  },
  {
    id: "ai-02",
    title: "Generative AI Foundations",
    title_i18n: { en: "Generative AI Foundations", hi: "जनरेटिव AI की बुनियाद", bn: "জেনারেটিভ AI-এর ভিত্তি" },
    provider: "Sample catalogue",
    providerUrl: "",
    affiliateUrl: "",
    category: "ai",
    language: ["English", "Hindi"],
    level: "Beginner",
    price: 999,
    priceLabel: "999",
    type: "paid",
    delivery: "sample",
    mode: "self-paced",
    duration: "3–6 months",
    durationHours: null,
    certificate: false,
    noCodingNeeded: true,
    aiForNonTech: true,
    careerOutcome: "Build practical familiarity with generative AI, prompting and everyday AI workflows.",
    lastVerified: "2026-09-21",
    status: "draft",
    sourceType: "sample",
    rating: "4.7",
    students: "Popular",
    featured: true,
    image: "https://images.pexels.com/photos/8197495/pexels-photo-8197495.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Build practical skills in generative AI, prompting and everyday AI workflows.",
    url: "#"
  },
  {
    id: "data-01",
    title: "Data Analytics with Python",
    title_i18n: { en: "Data Analytics with Python", hi: "Python के साथ Data Analytics", bn: "Python দিয়ে Data Analytics" },
    provider: "Sample catalogue",
    providerUrl: "",
    affiliateUrl: "",
    category: "engineering-cloud",
    language: ["English"],
    level: "Intermediate",
    price: 1499,
    priceLabel: "1499",
    type: "paid",
    delivery: "sample",
    mode: "self-paced",
    duration: "3–6 months",
    durationHours: null,
    certificate: false,
    noCodingNeeded: false,
    aiForNonTech: false,
    careerOutcome: "Build foundations in Python, data handling and practical analytics.",
    lastVerified: "2026-09-21",
    status: "draft",
    sourceType: "sample",
    rating: "4.8",
    students: "Trending",
    featured: true,
    image: "https://images.pexels.com/photos/5537934/pexels-photo-5537934.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "A structured route into Python, data handling and practical analytics.",
    url: "#"
  },
  {
    id: "eng-03",
    title: "Python for Beginners",
    title_i18n: { en: "Python for Beginners", hi: "शुरुआती लोगों के लिए Python", bn: "শুরুর জন্য Python" },
    provider: "Free / sample pathway",
    providerUrl: "",
    affiliateUrl: "",
    category: "engineering-cloud",
    language: ["English", "Hindi"],
    level: "Beginner",
    price: 0,
    priceLabel: "free",
    type: "free",
    delivery: "internal",
    mode: "self-paced",
    duration: "Self-paced",
    durationHours: null,
    certificate: false,
    noCodingNeeded: false,
    aiForNonTech: false,
    careerOutcome: "Build a foundation for further programming and data skills.",
    lastVerified: "2026-09-21",
    status: "draft",
    sourceType: "sample",
    rating: "4.7",
    students: "Free",
    featured: true,
    image: "https://images.pexels.com/photos/6209555/pexels-photo-6209555.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Start coding from zero with a practical, job-oriented introduction to Python.",
    url: "#"
  },
  {
    id: "exam-01",
    title: "SSC / Government Exam Foundation",
    title_i18n: { en: "SSC / Government Exam Foundation", hi: "SSC / सरकारी परीक्षा की तैयारी", bn: "SSC / সরকারি পরীক্ষার প্রস্তুতি" },
    provider: "Sample catalogue",
    providerUrl: "",
    affiliateUrl: "",
    category: "exam-prep",
    language: ["Hindi"],
    level: "Beginner",
    price: 799,
    priceLabel: "799",
    type: "paid",
    delivery: "sample",
    mode: "self-paced",
    duration: "6 months",
    durationHours: null,
    certificate: false,
    noCodingNeeded: true,
    aiForNonTech: false,
    careerOutcome: "Build a structured foundation for major government examinations.",
    lastVerified: "2026-09-21",
    status: "draft",
    sourceType: "sample",
    rating: "4.6",
    students: "Popular",
    featured: true,
    image: "https://images.pexels.com/photos/35551059/pexels-photo-35551059.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "A focused starting point for learners preparing for major government examinations.",
    url: "#"
  },
  {
    id: "english-01",
    title: "Spoken English for Work",
    title_i18n: { en: "Spoken English for Work", hi: "काम के लिए Spoken English", bn: "কাজের জন্য Spoken English" },
    provider: "Sample catalogue",
    providerUrl: "",
    affiliateUrl: "",
    category: "spoken-english",
    language: ["English", "Hindi"],
    level: "Beginner",
    price: 499,
    priceLabel: "499",
    type: "paid",
    delivery: "sample",
    mode: "self-paced",
    duration: "8 weeks",
    durationHours: null,
    certificate: false,
    noCodingNeeded: true,
    aiForNonTech: false,
    careerOutcome: "Improve workplace speaking, everyday communication and interview confidence.",
    lastVerified: "2026-09-21",
    status: "draft",
    sourceType: "sample",
    rating: "4.7",
    students: "Popular",
    featured: true,
    image: "https://images.pexels.com/photos/22915923/pexels-photo-22915923.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Everyday speaking, workplace communication and interview confidence.",
    url: "#"
  },
  {
    id: "trade-01",
    title: "Electrical Trade Foundations",
    title_i18n: { en: "Electrical Trade Foundations", hi: "इलेक्ट्रिकल ट्रेड की बुनियाद", bn: "ইলেকট্রিক্যাল ট্রেডের ভিত্তি" },
    provider: "Free / sample pathway",
    providerUrl: "",
    affiliateUrl: "",
    category: "vocational-trade",
    language: ["Hindi"],
    level: "Beginner",
    price: 0,
    priceLabel: "free",
    type: "free",
    delivery: "internal",
    mode: "self-paced",
    duration: "Self-paced",
    durationHours: null,
    certificate: false,
    noCodingNeeded: true,
    aiForNonTech: false,
    careerOutcome: "Build practical foundations for exploring electrical trade skills.",
    lastVerified: "2026-09-21",
    status: "draft",
    sourceType: "sample",
    rating: "4.6",
    students: "Free",
    featured: false,
    image: "https://images.pexels.com/photos/33925031/pexels-photo-33925031.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Practical foundations for learners exploring electrical trade skills.",
    url: "#"
  },
  {
    id: "cyber-01",
    title: "Cybersecurity Fundamentals",
    title_i18n: { en: "Cybersecurity Fundamentals", hi: "Cybersecurity की बुनियाद", bn: "Cybersecurity-এর ভিত্তি" },
    provider: "Sample catalogue",
    providerUrl: "",
    affiliateUrl: "",
    category: "cybersecurity",
    language: ["English"],
    level: "Beginner",
    price: 1299,
    priceLabel: "1299",
    type: "paid",
    delivery: "sample",
    mode: "self-paced",
    duration: "3–6 months",
    durationHours: null,
    certificate: false,
    noCodingNeeded: true,
    aiForNonTech: false,
    careerOutcome: "Understand basic cybersecurity concepts and the career landscape.",
    lastVerified: "2026-09-21",
    status: "draft",
    sourceType: "sample",
    rating: "4.8",
    students: "Trending",
    featured: true,
    image: "https://images.pexels.com/photos/4308096/pexels-photo-4308096.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Understand networks, threats, security hygiene and the cybersecurity career landscape.",
    url: "#"
  },

  /* ---------------- Verified public-provider starter catalogue ----------------
   * These are discovery listings only. Vidyarthi does not host the content.
   * URLs point to the official provider pages found during verification.
   */
  {
    id: "google-introduction-generative-ai",
    title: "Introduction to Generative AI",
    title_i18n: { en: "Introduction to Generative AI", hi: "Generative AI का परिचय", bn: "Generative AI-এর পরিচয়" },
    provider: "Google",
    providerUrl: "https://grow.google/intl/en_in/ai-skills/",
    affiliateUrl: "",
    category: "ai",
    language: ["English"],
    level: "Beginner",
    price: 0,
    priceLabel: "free",
    type: "free",
    delivery: "external",
    mode: "self-paced",
    duration: "Short course",
    durationHours: null,
    certificate: true,
    noCodingNeeded: true,
    aiForNonTech: true,
    careerOutcome: "Understand generative AI basics and begin using AI tools responsibly.",
    lastVerified: "2026-09-21",
    status: "published",
    sourceType: "public_provider",
    rating: "",
    students: "",
    featured: true,
    image: "",
    description: "A beginner-friendly, free introduction to generative AI from Google.",
    description_i18n: {
      en: "A beginner-friendly, free introduction to generative AI from Google.",
      hi: "Google की ओर से Generative AI की शुरुआती और मुफ्त जानकारी देने वाला कोर्स।",
      bn: "Google-এর পক্ষ থেকে Generative AI-এর সহজ ও বিনামূল্যের প্রাথমিক কোর্স।"
    },
    url: "https://grow.google/intl/en_in/ai-skills/"
  },
  {
    id: "google-introduction-llms",
    title: "Introduction to Large Language Models",
    title_i18n: { en: "Introduction to Large Language Models", hi: "Large Language Models का परिचय", bn: "Large Language Models-এর পরিচয়" },
    provider: "Google",
    providerUrl: "https://grow.google/intl/en_in/ai-skills/",
    affiliateUrl: "",
    category: "ai",
    language: ["English"],
    level: "Beginner",
    price: 0,
    priceLabel: "free",
    type: "free",
    delivery: "external",
    mode: "self-paced",
    duration: "Short course",
    durationHours: null,
    certificate: true,
    noCodingNeeded: true,
    aiForNonTech: true,
    careerOutcome: "Understand what large language models are and how generative AI systems use them.",
    lastVerified: "2026-09-21",
    status: "published",
    sourceType: "public_provider",
    rating: "",
    students: "",
    featured: true,
    image: "",
    description: "A free introductory course covering large language models and generative AI.",
    description_i18n: {
      en: "A free introductory course covering large language models and generative AI.",
      hi: "Large Language Models और Generative AI की शुरुआती समझ देने वाला मुफ्त कोर्स।",
      bn: "Large Language Models এবং Generative AI-এর প্রাথমিক ধারণা দেওয়া বিনামূল্যের কোর্স।"
    },
    url: "https://grow.google/intl/en_in/ai-skills/"
  },
  {
    id: "google-introduction-responsible-ai",
    title: "Introduction to Responsible AI",
    title_i18n: { en: "Introduction to Responsible AI", hi: "Responsible AI का परिचय", bn: "Responsible AI-এর পরিচয়" },
    provider: "Google",
    providerUrl: "https://grow.google/intl/en_in/ai-skills/",
    affiliateUrl: "",
    category: "ai",
    language: ["English"],
    level: "Beginner",
    price: 0,
    priceLabel: "free",
    type: "free",
    delivery: "external",
    mode: "self-paced",
    duration: "Short course",
    durationHours: null,
    certificate: true,
    noCodingNeeded: true,
    aiForNonTech: true,
    careerOutcome: "Understand responsible AI principles and why safe, ethical AI use matters.",
    lastVerified: "2026-09-21",
    status: "published",
    sourceType: "public_provider",
    rating: "",
    students: "",
    featured: false,
    image: "",
    description: "A free beginner course introducing responsible AI and Google's AI principles.",
    description_i18n: {
      en: "A free beginner course introducing responsible AI and Google's AI principles.",
      hi: "Responsible AI और Google के AI principles का परिचय देने वाला मुफ्त शुरुआती कोर्स।",
      bn: "Responsible AI এবং Google-এর AI principles-এর পরিচয় দেওয়া বিনামূল্যের প্রাথমিক কোর্স।"
    },
    url: "https://grow.google/intl/en_in/ai-skills/"
  },
  {
    id: "google-genai-educators",
    title: "Generative AI for Educators",
    title_i18n: { en: "Generative AI for Educators", hi: "शिक्षकों के लिए Generative AI", bn: "শিক্ষকদের জন্য Generative AI" },
    provider: "Google",
    providerUrl: "https://grow.google/intl/en_in/ai-skills/",
    affiliateUrl: "",
    category: "ai",
    language: ["English"],
    level: "Intermediate",
    price: 0,
    priceLabel: "free",
    type: "free",
    delivery: "external",
    mode: "self-paced",
    duration: "Short course",
    durationHours: null,
    certificate: true,
    noCodingNeeded: true,
    aiForNonTech: true,
    careerOutcome: "Learn practical ways to understand and teach generative AI concepts.",
    lastVerified: "2026-09-21",
    status: "published",
    sourceType: "public_provider",
    rating: "",
    students: "",
    featured: false,
    image: "",
    description: "A free course for educators who want to understand and teach generative AI concepts.",
    description_i18n: {
      en: "A free course for educators who want to understand and teach generative AI concepts.",
      hi: "शिक्षकों के लिए Generative AI को समझने और सिखाने पर केंद्रित मुफ्त कोर्स।",
      bn: "Generative AI বোঝা ও শেখানোর জন্য শিক্ষকদের উদ্দেশ্যে তৈরি বিনামূল্যের কোর্স।"
    },
    url: "https://grow.google/intl/en_in/ai-skills/"
  },
  {
    id: "microsoft-get-started-ai",
    title: "Get started with AI",
    title_i18n: { en: "Get started with AI", hi: "AI की शुरुआत करें", bn: "AI দিয়ে শুরু করুন" },
    provider: "Microsoft Learn",
    providerUrl: "https://learn.microsoft.com/en-us/training/modules/get-started-with-ai/",
    affiliateUrl: "",
    category: "ai",
    language: ["English"],
    level: "Beginner",
    price: 0,
    priceLabel: "free",
    type: "free",
    delivery: "external",
    mode: "self-paced",
    duration: "50 min",
    durationHours: 0.83,
    certificate: false,
    noCodingNeeded: true,
    aiForNonTech: true,
    careerOutcome: "Build basic AI vocabulary and practice prompting, summarising and image creation.",
    lastVerified: "2026-09-21",
    status: "published",
    sourceType: "public_provider",
    rating: "",
    students: "",
    featured: true,
    image: "",
    description: "A 50-minute beginner module covering basic AI terms and prompting best practices.",
    description_i18n: {
      en: "A 50-minute beginner module covering basic AI terms and prompting best practices.",
      hi: "50 मिनट का शुरुआती मॉड्यूल जिसमें AI की मूल बातें और prompting की अच्छी practices सिखाई जाती हैं।",
      bn: "৫০ মিনিটের প্রাথমিক মডিউল, যেখানে AI-এর মৌলিক ধারণা ও prompting-এর ভালো পদ্ধতি শেখানো হয়।"
    },
    url: "https://learn.microsoft.com/en-us/training/modules/get-started-with-ai/"
  },
  {
    id: "microsoft-introduction-ai-concepts",
    title: "Introduction to AI concepts",
    title_i18n: { en: "Introduction to AI concepts", hi: "AI concepts का परिचय", bn: "AI concepts-এর পরিচয়" },
    provider: "Microsoft Learn",
    providerUrl: "https://learn.microsoft.com/en-us/training/modules/get-started-ai-fundamentals/",
    affiliateUrl: "",
    category: "ai",
    language: ["English"],
    level: "Beginner",
    price: 0,
    priceLabel: "free",
    type: "free",
    delivery: "external",
    mode: "self-paced",
    duration: "40 min",
    durationHours: 0.67,
    certificate: false,
    noCodingNeeded: true,
    aiForNonTech: true,
    careerOutcome: "Understand core AI concepts, applications and responsible AI considerations.",
    lastVerified: "2026-09-21",
    status: "published",
    sourceType: "public_provider",
    rating: "",
    students: "",
    featured: true,
    image: "",
    description: "A 40-minute beginner module introducing AI, machine learning, deep learning and responsible AI.",
    description_i18n: {
      en: "A 40-minute beginner module introducing AI, machine learning, deep learning and responsible AI.",
      hi: "40 मिनट का शुरुआती मॉड्यूल जो AI, machine learning, deep learning और responsible AI से परिचित कराता है।",
      bn: "৪০ মিনিটের প্রাথমিক মডিউল যেখানে AI, machine learning, deep learning এবং responsible AI-এর পরিচয় দেওয়া হয়।"
    },
    url: "https://learn.microsoft.com/en-us/training/modules/get-started-ai-fundamentals/"
  },
  {
    id: "microsoft-explore-ai-basics",
    title: "Explore AI basics",
    title_i18n: { en: "Explore AI basics", hi: "AI की बुनियादी बातें", bn: "AI-এর প্রাথমিক ধারণা" },
    provider: "Microsoft Learn",
    providerUrl: "https://learn.microsoft.com/en-us/training/modules/explore-ai-basics/",
    affiliateUrl: "",
    category: "ai",
    language: ["English"],
    level: "Beginner",
    price: 0,
    priceLabel: "free",
    type: "free",
    delivery: "external",
    mode: "self-paced",
    duration: "58 min",
    durationHours: 0.97,
    certificate: false,
    noCodingNeeded: true,
    aiForNonTech: true,
    careerOutcome: "Build foundational AI literacy and understand how AI appears in everyday applications.",
    lastVerified: "2026-09-21",
    status: "published",
    sourceType: "public_provider",
    rating: "",
    students: "",
    featured: false,
    image: "",
    description: "A 58-minute beginner module exploring AI basics, history, machine learning and everyday applications.",
    description_i18n: {
      en: "A 58-minute beginner module exploring AI basics, history, machine learning and everyday applications.",
      hi: "58 मिनट का शुरुआती मॉड्यूल जिसमें AI की बुनियाद, इतिहास, machine learning और रोज़मर्रा के उपयोग समझाए जाते हैं।",
      bn: "৫৮ মিনিটের প্রাথমিক মডিউল যেখানে AI-এর ভিত্তি, ইতিহাস, machine learning এবং দৈনন্দিন ব্যবহার বোঝানো হয়।"
    },
    url: "https://learn.microsoft.com/en-us/training/modules/explore-ai-basics/"
  },
  {
    id: "microsoft-ai-toolbox-trainers",
    title: "An AI toolbox for trainers",
    title_i18n: { en: "An AI toolbox for trainers", hi: "प्रशिक्षकों के लिए AI toolbox", bn: "প্রশিক্ষকদের জন্য AI toolbox" },
    provider: "Microsoft Learn",
    providerUrl: "https://learn.microsoft.com/en-us/training/paths/ai-toolbox-for-trainers/",
    affiliateUrl: "",
    category: "ai",
    language: ["English"],
    level: "Beginner",
    price: 0,
    priceLabel: "free",
    type: "free",
    delivery: "external",
    mode: "self-paced",
    duration: "2 hr 53 min",
    durationHours: 2.88,
    certificate: false,
    noCodingNeeded: true,
    aiForNonTech: true,
    careerOutcome: "Help trainers and educators use AI tools to create engaging and inclusive learning experiences.",
    lastVerified: "2026-09-21",
    status: "published",
    sourceType: "public_provider",
    rating: "",
    students: "",
    featured: false,
    image: "",
    description: "A beginner learning path for trainers and educators exploring practical AI tools in learning environments.",
    description_i18n: {
      en: "A beginner learning path for trainers and educators exploring practical AI tools in learning environments.",
      hi: "शिक्षकों और trainers के लिए सीखने के माहौल में AI tools के व्यावहारिक उपयोग पर शुरुआती learning path।",
      bn: "শিক্ষক ও trainers-দের জন্য শিক্ষার পরিবেশে AI tools-এর ব্যবহার শেখার প্রাথমিক learning path।"
    },
    url: "https://learn.microsoft.com/en-us/training/paths/ai-toolbox-for-trainers/"
  },
  {
    id: "microsoft-ai-for-trainers",
    title: "Introduction to artificial intelligence for trainers",
    title_i18n: { en: "Introduction to artificial intelligence for trainers", hi: "प्रशिक्षकों के लिए Artificial Intelligence का परिचय", bn: "প্রশিক্ষকদের জন্য Artificial Intelligence-এর পরিচয়" },
    provider: "Microsoft Learn",
    providerUrl: "https://learn.microsoft.com/en-us/training/paths/introduction-to-artificial-intelligence-for-trainers/",
    affiliateUrl: "",
    category: "ai",
    language: ["English"],
    level: "Beginner",
    price: 0,
    priceLabel: "free",
    type: "free",
    delivery: "external",
    mode: "self-paced",
    duration: "2 hr 36 min",
    durationHours: 2.6,
    certificate: false,
    noCodingNeeded: true,
    aiForNonTech: true,
    careerOutcome: "Build foundational AI understanding and explore applications for teaching and learning.",
    lastVerified: "2026-09-21",
    status: "published",
    sourceType: "public_provider",
    rating: "",
    students: "",
    featured: false,
    image: "",
    description: "A beginner learning path covering AI foundations and practical applications in education and training.",
    description_i18n: {
      en: "A beginner learning path covering AI foundations and practical applications in education and training.",
      hi: "AI की बुनियाद और शिक्षा व training में उसके व्यावहारिक उपयोग पर केंद्रित शुरुआती learning path।",
      bn: "AI-এর ভিত্তি এবং শিক্ষা ও training-এ এর ব্যবহার নিয়ে তৈরি প্রাথমিক learning path।"
    },
    url: "https://learn.microsoft.com/en-us/training/paths/introduction-to-artificial-intelligence-for-trainers/"
  }
];
